import java.util.Random ; 

public class Dice {
    
    public static int generateNumber() 
    { 
        Random rand= new Random() ; 
        int num= rand.nextInt(1, 7 ) ; 
        System.out.println("Number Generated By Dice Is: "+ num+ "\n" ) ; 
        return num ; 
    } 
} 
